In [22]:
import numpy as np
import pandas as pd

In [23]:
# Q1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

arr=np.arange(0,6,1)
arr.dtype

dtype('int32')

In [25]:
'''q2.  Given a NumPy array 'arr', check if its data type is float64.
arr = np.array([1.5, 2.6, 3.7])''' 

arr=np.array([1.5, 2.6, 3.7])
arr.dtype                

dtype('float64')

In [8]:
'''q3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.'''
arr=np.array([2+1j, 3+1j,4+1j])
arr.dtype

dtype('complex128')

In [9]:
'''q4 Convert an existing NumPy array 'arr' of integers to float32 data type.'''
arr=np.arange(0,6,1)
arr.astype('float32')

array([0., 1., 2., 3., 4., 5.], dtype=float32)

In [26]:
''''Q'5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.'''

arr=np.array([1.5, 2.6, 3.7])
print(arr.dtype)
arr.astype('float32')

float64


array([1.5, 2.6, 3.7], dtype=float32)

In [27]:
'''Q6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data 
type.'''


def array_attributes(arr):
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype
    return shape, size, dtype  
arr=np.array([1.5, 2.6, 3.7])
print(arr)
print(array_attributes(arr))    



[1.5 2.6 3.7]
((3,), 3, dtype('float64'))


In [28]:
'''Q7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality'''

def array_attributes(arr):
    dimension=arr.ndim
    return dimension
arr=np.array([1.5, 2.6, 3.7])
print(arr)
print(array_attributes(arr))     

[1.5 2.6 3.7]
1


In [29]:
''' Q8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total 
size in bytes.'''

def array_attributes(arr):
    itemsize=arr.size
    bytes=arr.nbytes
    return itemsize, bytes
arr=np.array([1.5, 2.6, 3.7])
print(arr)
print(array_attributes(arr))   


[1.5 2.6 3.7]
(3, 24)


In [30]:
'''Q 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.'''

def array_strides(arr):
     arr_strides= arr.strides
     return arr_strides
arr=np.array([1.5, 2.6, 3.7])
print(arr)
print(array_strides(arr))  


[1.5 2.6 3.7]
(8,)


In [31]:
'''Q 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.'''
import numpy as np
def shape_stride_relationship(arr):
    return arr.shape, arr.strides
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
shape, strides = shape_stride_relationship(arr)
print("Array shape:", shape)
print("Array strides:", strides)

Array shape: (3, 3)
Array strides: (12, 4)


In [32]:
'''Q 11 Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of 
zeros with `n` elements.'''

def create_zeros_array(n):
   arr=np.zeros(n)
   return arr
print(create_zeros_array(6))

[0. 0. 0. 0. 0. 0.]


In [33]:
# Q 12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.
def create_ones_matrix(rows,cols):
   arr=np.ones((rows,cols))
   return arr
print(create_ones_matrix(3,4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [34]:
'''Q 13 Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and 
creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified 
`step`.
'''
def generate_range_array(start, stop, step):
   arr=np.arange(start, stop, step)
   return arr
print(generate_range_array(0, 11, 2))


[ 0  2  4  6  8 10]


In [35]:
'''14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as 
arguments and generates a NumPy array with num equally spaced values between `start` and `stop` 
(inclusive).'''

def generate_linear_space(start, stop, num):
   arr=np.linspace(start, stop, num)
   return arr
print(generate_linear_space(1,12,10))

[ 1.          2.22222222  3.44444444  4.66666667  5.88888889  7.11111111
  8.33333333  9.55555556 10.77777778 12.        ]


In [36]:
''' Q 15 Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square 
identity matrix of size `n x n` using `numpy.eye`.'''

def create_identity_matrix(n):
    arr=np.eye(n)
    return arr
print(create_identity_matrix(5))


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [37]:
 # Q16. Write a function that takes a Python list and converts it into a NumPy array.

l=[1,2,3,4,5,6,7,8]
arr=np.array(l)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
''' Q 17 Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the 
same data'''

original_array = np.array([[1, 2, 3], [4, 5, 6]])
view_array = original_array.view()
view_array[0, 0] = 100
print(original_array)
print("**********************")
print(view_array)


[[100   2   3]
 [  4   5   6]]
**********************
[[100   2   3]
 [  4   5   6]]


In [39]:
#  18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.
import numpy as np
def concatenate_arrays(arr1, arr2, axis=0):
  return np.concatenate((arr1, arr2), axis=0)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
concatenated_array = np.concatenate((arr1, arr2), axis=0)
print(concatenated_array)


[[1 2]
 [3 4]
 [5 6]]


In [40]:
'''19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.'''

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr2 = np.array([[7, 8],
                 [9, 10]])
concatenated_array = np.concatenate((arr1, arr2), axis=1)

print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)
print("\nConcatenated array horizontally:")
print(concatenated_array)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8]
 [ 9 10]]

Concatenated array horizontally:
[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


In [41]:
'''20. Write a function that vertically stacks multiple NumPy arrays given as a list.'''
def stack_arrays_vertically(arrays):
    return np.vstack(arrays)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr3 = np.array([[9, 10], [11, 12]])

stacked_array = stack_arrays_vertically([arr1, arr2, arr3])
print(stacked_array)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [42]:
"21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size."

def create_integer_array(start, stop, step):
    return np.arange(start, stop+1, step, dtype=int)
start = 0
stop = 40
step = 5
result = create_integer_array(start, stop, step)
print(result)

[ 0  5 10 15 20 25 30 35 40]


In [11]:
'''Q22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 
(inclusive).'''
#22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).


def generate_equally_spaced_values():
    return np.linspace(0, 1, 10)
result = generate_equally_spaced_values()
print(result)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [43]:
#23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).


def generate_logarithmically_spaced_values():
    return np.logspace(start=np.log10(1), stop=np.log10(1000), num=5)
result = generate_logarithmically_spaced_values()
print(result)


[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [13]:
#24.Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100 .


# Create a NumPy array of random integers between 1 and 100
np.random.seed(42)  # For reproducibility
data = np.random.randint(1, 101, size=(5, 3))

# Create a Pandas DataFrame using the NumPy array
df = pd.DataFrame(data, columns=['Column1', 'Column2', 'Column3'])

print(df)

   Column1  Column2  Column3
0       52       93       15
1       72       61       21
2       83       87       75
3       75       88      100
4       24        3       22


In [44]:
# 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

def replace_negative_with_zeros(df, column_name):
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df
data = {'A': [1, 2, -3, 4, -5],
        'B': [5, -6, 7, -8, 9]}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

df = replace_negative_with_zeros(df, 'A')
df=replace_negative_with_zeros(df,'B')

print("\nDataFrame with negative values replaced by zeros:")
print(df)

Original DataFrame:
   A  B
0  1  5
1  2 -6
2 -3  7
3  4 -8
4 -5  9

DataFrame with negative values replaced by zeros:
   A  B
0  1  5
1  2  0
2  0  7
3  4  0
4  0  9


In [45]:
'''26. Access the 3rd element from the given NumPy array.
arr = np.array([10, 20, 30, 40, 50])'''

arr = np.array([10, 20, 30, 40, 50])
third_element = arr[2]

print("Third element:", third_element)

Third element: 30


In [46]:
''''27. Retrieve the element at index (1, 2) from the 2D NumPy array.arr_2d = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])'''


arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d[1, 2]


6

In [47]:
#28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
arr = np.array([3, 8, 2, 10, 5, 7])
arr[arr > 5]

array([ 8, 10,  7])

In [48]:
#29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[2:6]

array([3, 4, 5, 6])

In [107]:
#30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array


arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
sub_array = arr_2d[0:2, 1:]
sub_array


array([[2, 3],
       [5, 6]])

In [49]:
#31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

def extract_elements_by_indices(arr_2D, indices):
    return arr_2D.ravel()[indices]

# Example usage:
arr_2D = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

indices = np.array([1, 4, 2, 5, 7])

result = extract_elements_by_indices(arr_2D, indices)
print("Extracted elements based on indices:", result)

Extracted elements based on indices: [2 5 3 6 8]


In [50]:
#32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.
import numpy as np

def filter_elements_greater_than_threshold(arr, threshold):
    return arr[arr > threshold]

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
threshold = 5

result = filter_elements_greater_than_threshold(arr, threshold)
print("Filtered elements greater than", threshold, ":", result)

Filtered elements greater than 5 : [6 7 8 9]


In [51]:
'''Q 33 Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three 
separate arrays for each dimension.'''

def extract_elements_3d(array, indices_dim1, indices_dim2, indices_dim3):
   indices = (indices_dim1, indices_dim2, indices_dim3)
   extracted_elements = array[indices]
   return extracted_elements
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
indices_dim1 = np.array([0, 1])
indices_dim2 = np.array([0, 1])
indices_dim3 = np.array([1, 2])
extract_elements_3d(arr_3d, indices_dim1, indices_dim2, indices_dim3)

array([ 2, 12])

In [52]:
#34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.
import numpy as np

def elements_satisfying_conditions(arr, condition1, condition2):
    return arr[np.logical_and(condition1, condition2)]
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9,12,32,64])
condition1 = arr > 3
condition2 = arr % 2 == 0

result = elements_satisfying_conditions(arr, condition1, condition2)
print("Elements satisfying both conditions:")
print(result)


Elements satisfying both conditions:
[ 4  6  8 12 32 64]


In [53]:
'''35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.
import numpy as np'''

def extract_elements_from_2d_array(arr_2d, row_indices, col_indices):
    return arr_2d[row_indices, col_indices]

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 0, 2])

result = extract_elements_from_2d_array(arr_2d, row_indices, col_indices)
print("Extracted elements:")
print(result)

Extracted elements:
[2 4 9]


In [54]:
''' 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting '''

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
arr1=arr+5
arr1

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [55]:
'''37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the 
corresponding element in arr1 using NumPy broadcasting'''

arr1 = np.array([[1, 2, 3]])

arr2 = np.array([
    [4, 5, 6, 7],
    [8, 9, 10, 11],
    [12, 13, 14, 15]
])

# Multiply each row of arr2 by the corresponding element in arr1 using broadcasting
result = arr2 * arr1.T

print(result)


[[ 4  5  6  7]
 [16 18 20 22]
 [36 39 42 45]]


In [56]:
arr3=arr2.reshape(4,3)
arr4=arr1*arr3
arr4

array([[ 4, 10, 18],
       [ 7, 16, 27],
       [10, 22, 36],
       [13, 28, 45]])

In [108]:
'''Q.38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using 
NumPy broadcasting'''


arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9],
                 [10, 11, 12]])
arr_add=arr1.T+arr2
arr_add




array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])

In [57]:
'''39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy 
broadcasting.'''

arr2 = np.array([[1, 2, 3]])
arr1 = np.array([[1],
                 [4],
                 [7]])
arr_add=arr1+arr2
arr_add

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [109]:
'''40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy 
broadcasting. Handle the shape incompatibility'''


arr1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

arr2 = np.array([
    [7, 8],
    [9, 10]
])

# Reshape arr2 to (2, 2, 1)
arr2_reshaped = arr2[:, :, np.newaxis]

# Use broadcasting
result = arr1 * arr2_reshaped

print(result)



[[[ 7 14 21]
  [32 40 48]]

 [[ 9 18 27]
  [40 50 60]]]


In [58]:
'''41. Calculate column wise mean for the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])'''

arr = np.array([[1, 2, 3], [4, 5, 6]])
column_mean = np.mean(arr, axis=0)
print(column_mean)


[2.5 3.5 4.5]


In [59]:
'''Q 42 Find maximum value in each row of the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])'''

arr = np.array([[1, 2, 3], [4, 5, 6]])
arr1=np.max(arr,axis=1)
arr1

array([3, 6])

In [60]:
'''43. For the given array, find indices of maximum value in each column.
arr = np.array([[1, 2, 3], [4, 5, 6]])'''

arr = np.array([[1, 2, 3], [4, 5, 6]])
arr=np.argmax(arr,axis=0)
arr

array([1, 1, 1], dtype=int64)

In [61]:
#44. For the given array, apply custom function to calculate moving sum along rows.
arr = np.array([[1, 2, 3], [4, 5, 6]])

arr = np.array([[1, 2, 3], [4, 5, 6]])
arr_max1=np.cumsum(arr,axis=0)
arr_max1  



array([[1, 2, 3],
       [5, 7, 9]])

In [62]:
'''45. In the given array, check if all elements in each column are even.
arr = np.array([[2, 4, 6], [3, 5, 7]])'''

arr = np.array([[1, 2, 3], [4, 5, 6]])
arr%2==0




array([[False,  True, False],
       [ True, False,  True]])

In [63]:
'''46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the 
reshaped matrix. original_array = np.array([1, 2, 3, 4, 5, 6])'''

original_array = np.array([1, 2, 3, 4, 5, 6])
reshaped_matrix = np.matrix(original_array.reshape(3,2))
reshaped_matrix



matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [65]:
'''47. Create a function that takes a matrix as input and returns the flattened array.'''

def flatten_matrix(input_matrix):
    arr=input_matrix.flatten()
    return arr
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
flattern_M=input_matrix.flatten()
flattern_M
    


array([1, 2, 3, 4, 5, 6])

In [66]:
# 48 Write a function that concatenates two given arrays along a specified axis.

def concatenate(array1, array2, axis):
  arr=np.concatenate((array1, array2), axis=axis)
  return arr
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
concatenate(array1, array2, axis=1)



array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [67]:
'''49. Create a function that splits an array into multiple sub-arrays along a specified axis'''
def split_array(original_array, num, axis):
  arr=np.split(original_array, num, axis=axis)
  return arr
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
split_q=np.split(original_array,3,axis=1)
split_q


[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [69]:
'''Q50-Write a function that inserts and then deletes elements from a given array at specified indices.
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]
'''
def insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete):
    array_list = original_array.tolist()
    sorted_inserts = sorted(zip(indices_to_insert, values_to_insert))
    offset = 0
    for index, value in sorted_inserts:
        array_list.insert(index + offset, value)
        offset += 1

    modified_array = np.array(array_list)

    sorted_deletes = sorted(indices_to_delete, reverse=True)


    for index in sorted_deletes:
        modified_array = np.delete(modified_array, index)

    return modified_array

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

result_array = insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print(result_array)


[ 1 10  4 11  5]


In [68]:
'''51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. 
Perform element-wise addition between `arr1` and `arr2`.'''
arr1=np.random.randint(0,11,10)
arr2=np.arange(1,11,1)
arr_add=arr1+arr2
arr_add

array([ 5,  3, 10,  9,  6, 10,  7, 17, 14, 18])

In [70]:
'''52 Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. 
Perform element-wise addition between `arr1` and `arr2`.'''
arr1=np.arange(10,0,-1)
arr2=np.arange(1,11,1)
arr_sub=arr1-arr2
arr_sub

array([ 9,  7,  5,  3,  1, -1, -3, -5, -7, -9])

In [71]:
''' 53 Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. 
Perform element-wise multiplication between `arr1` and `arr2'
  '''
arr1=np.random.randint(0,6,5)
print(arr1)
arr2=np.arange(1,6,1)
print(arr2)
arr_mul=arr1*arr2
arr_mul


[0 2 2 1 3]
[1 2 3 4 5]


array([ 0,  4,  6,  4, 15])

In [72]:
'''54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 
to 5. Perform element-wise division of `arr1` by `arr2`.'''

arr1=np.arange(2,11,2)
arr2=np.arange(1,6,1)
arr_div=arr1/arr2
arr_div


array([2., 2., 2., 2., 2.])

In [73]:
'''55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers 
reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wis'''

arr1=np.arange(1,6,1)
arr2=arr1[::-1]
print(arr2)
arr_power=np.power(arr1,arr2)
arr_power


[5 4 3 2 1]


array([ 1, 16, 27, 16,  5])

In [74]:
'''56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])'''

def count_substring_occurrences(arr, substring):
    count = np.char.count(arr, substring)
    total_count = np.sum(count)
    return total_count
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'
print(count_substring_occurrences(arr, substring))




3


In [75]:
'''57. Write a function that extracts uppercase characters from a NumPy array of strings.
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT']))'''


def extract_uppercase_characters(arr):
    return [char for string in arr for char in string if char.isupper()]
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
uppercase_characters = extract_uppercase_characters(arr)
print(uppercase_characters)

    

['H', 'W', 'O', 'A', 'I', 'G', 'P', 'T']


In [76]:
''''58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])'''


def replace_substring(arr, old_substring, new_substring):
  arr=np.char.replace(arr, old_substring, new_substring)
  return arr
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
old_substring = 'apple'
new_substring = 'orange'
print(replace_substring(arr, old_substring, new_substring))


['orange' 'banana' 'grape' 'pineorange']


In [77]:
'''59. Write a function that concatenates strings in a NumPy array element-wise.
arr1 = np.array(['Hello', 'World'])

arr2 = np.array(['Open', 'AI'])'''

def concatenate_arrays(arr1, arr2, axis):
  arr=np.concatenate((arr1, arr2), axis=axis)
  return arr
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
print(concatenate_arrays(arr1, arr2, axis=0))

['Hello' 'World' 'Open' 'AI']


In [78]:
''' q 60 Write a function that finds the length of the longest string in a NumPy array.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])'''

def longest_string_length(arr):
  arr=max(len(s) for s in arr)
  return arr
arr1 = np.array(['apple', 'banana', 'grape', 'pineapple'])
longest_string_length(arr1)




9

In [79]:
'''Q61 Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and 
standard deviation of the dataset using NumPy's functions.'''

arr1= np.random.randint(1,1001,100)
arr1
arr2=np.mean(arr1)
print(arr2)
arr3=np.median(arr1)
print(arr3)
arr4=np.var(arr1)
print(arr4)
arr5=np.std(arr1)
print(arr5)

506.87
502.0
86882.41309999999
294.7582282142434


In [80]:
'''62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the 
dataset.'''
arr1= np.random.randint(1,101,50)
arr1
arr2= np.percentile(arr1, [25,75])
arr2

array([23., 76.])

In [81]:
'''63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these 
arrays using NumPy's `corrcoef` function.'''


arr1=np.random.randint(1,101,50)
arr2=np.random.randint(1,101,50)
arr3=np.corrcoef(arr1, arr2)
arr3

array([[1.       , 0.2450498],
       [0.2450498, 1.       ]])

In [82]:
'''64. Create two matrices and perform matrix multiplication using NumPy's `dot` function'''

mat1=np.array([[2,6,7],[6,7,8]] )
mat2=np.array([[1,2],[3,4],[5,6]])
mat3=np.dot(mat1,mat2)
mat3

array([[55, 70],
       [67, 88]])

In [83]:
'''  65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th 
percentiles along with the first and third quartiles.'''

arr1= np.random.randint(1,101,50)
arr1
arr2= np.percentile(arr1, [10,25,50,75,90])
arr2




array([ 8.8 , 23.25, 41.  , 78.75, 93.1 ])

In [84]:
'''  66. Create a NumPy array of integers and find the index of a specific element.'''

arr=np.array([1,2,3,4,5])
element_to_find = 5
index = np.where(arr == element_to_find)[0]
print("Index of", element_to_find, ":", index)


Index of 5 : [4]


In [85]:
'''67. Generate a random NumPy array and sort it in ascending order.'''
arr1=np.array([1,4,9,8,5])
print(arr1)
print("\n ****************** ")
arr2=np.sort(arr1)
print(arr2)

[1 4 9 8 5]

 ****************** 
[1 4 5 8 9]


In [86]:
'''.q.68 'Filter elements >20  in the given NumPy array 
arr = np.array([12, 25, 6, 42, 8, 30])'''

arr = np.array([12, 25, 6, 42, 8, 30])
arr1=arr[arr>20]
arr1


array([25, 42, 30])

In [87]:
'''69. Filter elements which are divisible by 3 from a given NumPy array
arr = np.array([1, 5, 8, 12, 15]) '''

arr = np.array([1, 5, 8, 12, 15])
arr1=arr[arr%3==0]
arr1


array([12, 15])

In [110]:
'''70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
arr = np.array([10, 20, 30, 40, 50])'''

arr = np.array([1, 5, 18, 12, 15,40,35,25,20,15])
arr1=arr[(arr>=20)&(arr<=40)]
arr1



array([40, 35, 25, 20])

In [88]:
'''71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
arr = np.array([1, 2, 3])'''

arr = np.array([1, 2, 3])
arr_4=np.byte(arr)
byte_order = arr.dtype.byteorder
print("Byte order:", byte_order)

Byte order: =


In [89]:
# 72. # For the given NumPy array, perform byte swapping in place using `byteswap()`


arr = np.array([1, 2, 3], dtype=np.int32)
arr1=arr.byteswap(True)
arr1


array([16777216, 33554432, 50331648])

In [92]:
'''73. For the given NumPy array, swap its byte order without modifying the original array using 
`newbyteorder()`.'''

arr = np.array([1, 2, 3], dtype=np.int32)
arr1=arr.newbyteorder()
arr1


array([16777216, 33554432, 50331648], dtype='>i4')

In [95]:
'''74. For the given NumPy array and swap its byte order conditionally based on system endianness using 
newbyteorder()'''
arr = np.array([1, 2, 3], dtype=np.int32)
arr1=arr.byteswap(True)
arr2=arr.newbyteorder()
arr2

array([1, 2, 3], dtype='>i4')

In [96]:
'''75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` 
attribute `byteorder`.
arr = np.array([1, 2, 3], dtype=np.int32)'''

arr = np.array([1, 2, 3], dtype=np.int32)
arr1=arr.dtype.byteorder
arr1

'='

In [99]:
'''76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify 
an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.''' 

arr=np.arange(1,11,1)
copy_arr=arr.copy()
modify_arr=arr
modify_arr[1]=34
print(modify_arr)
print(arr)
print("************************************************")
copy_arr[2]=22
print(arr)
print(copy_arr)


[ 1 34  3  4  5  6  7  8  9 10]
[ 1 34  3  4  5  6  7  8  9 10]
************************************************
[ 1 34  3  4  5  6  7  8  9 10]
[ 1  2 22  4  5  6  7  8  9 10]


In [97]:
'''77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from 
the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`'''

matrix=np.random.randint(1,3,(3,3))
print(matrix)
view_slice = matrix[0:2]
print(view_slice)
view_slice[0,0]=30
view_slice

[[2 2 2]
 [2 2 1]
 [2 1 1]]
[[2 2 2]
 [2 2 1]]


array([[30,  2,  2],
       [ 2,  2,  1]])

In [98]:
'''78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice 
`view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.'''
matrix=np.arange(1,13).reshape(4,3)
print(matrix)
view_b = matrix[0:2]
print(view_b)
view_b+=5
print(view_b)




[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[1 2 3]
 [4 5 6]]
[[ 6  7  8]
 [ 9 10 11]]


In [100]:
'''79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view 
`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it 
reflects changes in the original `orig_array'''

orig_array=np.arange(1,9).reshape(2,4)
reshaped_view=np.arange(1,9).reshape(4,2)
print(reshaped_view)
reshaped_view[1,1]=36
print(reshaped_view)



[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[ 1  2]
 [ 3 36]
 [ 5  6]
 [ 7  8]]


In [101]:
'''80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of 
elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.'''

data=np.random.randint(1,13,(3,4))
print(data)
print('**********************************8')
data_copy=data[data>5].copy()
print(data_copy)
print('#####################################')
data_copy[0]=5
print(data_copy)

[[4 1 4 1]
 [5 4 8 8]
 [7 3 1 1]]
**********************************8
[8 8 7]
#####################################
[5 8 7]


In [102]:
'''81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction 
operations between them.'''
matrix1=np.arange(1,13).reshape(4,3)
matrix2=np.arange(11,23).reshape(4,3)
matrix3=matrix1+matrix2
matrix4=matrix2-matrix1
print(matrix3)
print("&&&&&&&&&&&&&&&&&&&&&&&&&&")
print(matrix4)

[[12 14 16]
 [18 20 22]
 [24 26 28]
 [30 32 34]]
&&&&&&&&&&&&&&&&&&&&&&&&&&
[[10 10 10]
 [10 10 10]
 [10 10 10]
 [10 10 10]]


In [103]:
#82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

C = np.array([[1, 2],
              [3, 4],
              [5, 6]])
D = np.array([[7, 8, 9, 10],
              [11, 12, 13, 14]])
result = np.dot(C, D)
print(result)

[[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


In [104]:
#83. Create a matrix `E` and find its transpose.

E = np.array([[1, 2],
              [3, 4],
              [5, 6]])
F=E.T
F

array([[1, 3, 5],
       [2, 4, 6]])

In [105]:
# 84 Generate a square matrix `F` and compute its determinant

n_array = np.array([[50, 29], [30, 44]]) 
  
print("Numpy Matrix is:") 
print(n_array) 
det = np.linalg.det(n_array) 
print("\nDeterminant of given 2X2 matrix:") 
print(int(det)) 




Numpy Matrix is:
[[50 29]
 [30 44]]

Determinant of given 2X2 matrix:
1330


In [106]:
#85. Create a square matrix `G` and find its inverse.

n_array = np.array([[50, 29], [30, 44]]) 
print("Numpy Matrix is:") 
print(n_array) 
inv = np.linalg.inv(n_array) 
inv




Numpy Matrix is:
[[50 29]
 [30 44]]


array([[ 0.03308271, -0.02180451],
       [-0.02255639,  0.03759398]])